### ISSUE TITLE
Running 'demo.py' with 24GB of GPU RAM

### ISSUE THREAD

**Issue by KevinCain** [princeton-vl/CER-MVS#1]
As an early fan of RAFT, I'm delighted at your work to extend it from stereo to MVS. Your paper is wonderfully readable: I appreciate your novel directions. In particular I appreciate that your approach allows inference to use a different number of image neighbors than were used in training, and for me your novel point cloud stitching is a welcome shift away from relying on fusible or similar approaches.

I had no trouble obtaining depths (inference memory: ~4 GB, per view time: ~1 second on RTX3090), masks and a final model for DTU data. For the 'Ignatius' T&T data, I can compute depths successfully, thereafter CER-MVS exits at 'inference memory: 23947 MB' with a GPU out-of-memory error:

`RuntimeError: CUDA out of memory. Tried to allocate 544.00 MiB (GPU 0; 23.70 GiB total capacity; 20.07 GiB already allocated; 535.56 MiB free; 21.47 GiB reserved in total by PyTorch)`

I believe you also tested on the RTX3090's 24GB GPU RAM. I'm trying to understand why it worked in your tests and failed in my environment, using the same card. Any suggestions to duplicate your results?

Also, based on the DTU output I had to do a bit of point culling beyond the subject region in order to frame the point cloud. Are there any options for bounding-box culling within CER-MVS?

Thanks again for your work, your excellent paper, and making your code available for testing.

**Comment by mazeyu** [comment]
Hi Kevin. I tested on a RTX3090 again and it works fine. However, the memory usage is pretty near the limit so it is likely it will run out of memory for some reasons I don't know.  If this happens, it is in the double resolution inference. I would suggest reducing the number of frames in demo.py line 45 from 25 to 24, 23 etc, which should not harm the performance much. Or try running on a GPU with more memory.
As for culling for visualization, I have some script essentially just removing points outside a ball. They are so simple that I think you can write your own.

**Comment by KevinCain** [comment]
Thanks @mazeyu, I'll try reducing the frame number as you suggest. As you intuited, I can manage to compute a few of the full-resolution depth maps before one of the frames pushes the memory over the line. The half-resolution depth inference is <6GB of GPU RAM, so as you point out that's not a problem:

```
T&T (Ignatius, ~262 images)
½ res inference memory: ~5.4 GB
½ res per view time: ~1.4 seconds on RTX 3090
Full res inference memory: ~23.8+ GB
Full res per view time: ~8 seconds on RTX 3090
```

**Comment by mazeyu** [comment]
another solution is to make use of the subset option in inference function, e.g., if it crashes at frame 10, then pass subset=(10,262,1) (which means start, end, step). But it is troublesome as it's hard to predict when it crashes.
